name: uavgeoloc
dependencies:
  - backcall=0.2.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates
  - cairo=1.14.12
  - certifi
  - cudatoolkit
  - cycler=0.10.0
  - dbus=1.13.18
  - decorator=5.0.9
  - entrypoints=0.3
  - expat=2.4.1
  - ffmpeg=4.0
  - fontconfig=2.13.1
  - freeglut=3.0.0
  - freetype=2.10.4
  - glib=2.63.1
  - graphite2=1.3.14
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - intel-openmp=2018.0.3
  - ipykernel=5.3.4
  - ipython=7.26.0
  - ipython_genutils=0.2.0
  - jasper=2.0.14
  - jedi=0.18.0
  - jpeg=9b
  - jupyter_client=7.0.1
  - jupyter_core=4.7.1
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libedit=3.1.20210714
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - matplotlib-inline=0.1.2
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - ninja=1.10.2
  - numpy
  - numpy-base
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1q
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.2.2
  - pixman=0.40.0
  - prompt-toolkit=3.0.17
  - ptyprocess=0.7.0
  - py-opencv=3.4.2
  - pygments=2.10.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.7.1
  - python-dateutil=2.8.2
  - pyyaml=5.4.1
  - pyzmq=22.2.1
  - qt=5.9.7
  - readline=7.0
  - scipy=1.6.2
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - typing_extensions=3.10.0.0
  - wcwidth=0.2.5
  - wheel=0.37.0
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.4.9
  - pytorch=1.7.1
  - torchvision=0.8.2
